version: '3.7'
services:
  bot:
    build:
      context: /bot
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure

  server:
    build:
      context: /background
      dockerfile: Dockerfile
    env_file:
      - 2.env
    restart: on-failure
